services:
  - type: web
    name: telegram-video-bot-advanced
    env: python
    plan: free
    buildCommand: |
      pip install -r requirements.txt
      sudo apt-get update
      sudo apt-get install -y ffmpeg
    startCommand: python bot.py
    envVars:
      - key: BOT_TOKEN
        sync: false